// Project LOOP - Voice of Customer (VoC) Intelligence Reports (React JavaScript)
import React, { useState } from 'react';
import confetti from 'canvas-confetti';
import { 
  FileText, 
  Sparkles, 
  Printer, 
  TrendingUp, 
  AlertTriangle, 
  CheckCircle2, 
  Quote, 
  Calendar, 
  ArrowRight,
  Download
} from 'lucide-react';
import { synthesizeVoCReport } from '../utils/aiEngine';

export default function VocReports({
  feedbackList = [],
  themesList = [],
  reportsList = [],
  currentUser,
  checkPermission,
  onSaveReport
}) {
  const [period, setPeriod] = useState('Last 30 Days');
  const [generating, setGenerating] = useState(false);
  const [activeReport, setActiveReport] = useState(reportsList[0] || null);

  const handleGenerate = () => {
    if (!checkPermission('generate Voice of Customer reports', ['ADMIN', 'ANALYST'])) return;
    setGenerating(true);

    setTimeout(() => {
      const rep = synthesizeVoCReport(period, feedbackList, themesList, currentUser.name);
      onSaveReport(rep);
      setActiveReport(rep);
      setGenerating(false);
      try {
        confetti({ particleCount: 70, spread: 60, origin: { y: 0.3 } });
      } catch (e) {}
    }, 1200);
  };

  return (
    <div className="space-y-6">
      {/* Header (No print) */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-2 border-b border-slate-800/80 no-print">
        <div>
          <h1 className="text-2xl font-extrabold tracking-tight text-white flex items-center gap-2">
            <span>Voice-of-Customer (VoC) Reports (AI4)</span>
            <span className="text-xs font-bold px-2.5 py-0.5 rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/30">
              Executive Synthesis
            </span>
          </h1>
          <p className="text-xs text-gray-400 mt-1">
            Automate periodic leadership digests synthesizing customer sentiment shifts, verbatim quotes, and prioritized actions.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <select
            value={period}
            onChange={(e) => setPeriod(e.target.value)}
            className="bg-slate-800 text-white rounded-xl px-3 py-2 border border-slate-700 text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="Last 30 Days">Last 30 Days</option>
            <option value="Q3 2026">Q3 2026 Cycle</option>
            <option value="Year to Date">Year to Date (YTD)</option>
          </select>

          <button
            onClick={handleGenerate}
            disabled={generating}
            className="bg-gradient-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-400 text-white text-xs font-bold px-4 py-2 rounded-xl shadow-lg shadow-indigo-600/30 flex items-center gap-1.5 transition-all"
          >
            <Sparkles className="w-4 h-4" />
            <span>{generating ? 'Synthesizing with Claude AI...' : '✨ Generate VoC Report'}</span>
          </button>
        </div>
      </div>

      {/* Main Report View */}
      {activeReport ? (
        <div 
          id="printable-report" 
          className="bg-slate-900/90 border border-slate-800 rounded-3xl p-8 space-y-8 shadow-2xl"
        >
          {/* Report Top Header */}
          <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 pb-6">
            <div>
              <span className="text-[11px] font-bold uppercase tracking-widest text-indigo-400">
                Project LOOP · Executive Intelligence Digest
              </span>
              <h2 className="text-2xl font-black text-white mt-1">
                {activeReport.title}
              </h2>
              <div className="text-xs text-gray-400 mt-1 flex items-center gap-3">
                <span>Generated by <strong className="text-gray-200">{activeReport.generatedBy}</strong></span>
                <span>•</span>
                <span>{activeReport.createdAt}</span>
                <span>•</span>
                <span className="text-emerald-400 font-semibold">{activeReport.totalFeedback} Signals Analyzed</span>
              </div>
            </div>

            <button
              onClick={() => window.print()}
              className="no-print bg-slate-800 hover:bg-slate-700 text-white text-xs font-bold px-4 py-2 rounded-xl border border-slate-700 flex items-center gap-2 transition-colors"
            >
              <Printer className="w-4 h-4" />
              <span>Print / Export PDF</span>
            </button>
          </div>

          {/* Executive Summary */}
          <div className="space-y-3">
            <h3 className="text-xs font-extrabold uppercase tracking-wider text-gray-400">
              1. Executive Summary
            </h3>
            <div className="bg-slate-800/60 border border-slate-700/80 p-5 rounded-2xl text-xs text-gray-200 leading-relaxed font-normal shadow-inner">
              {activeReport.executiveSummary}
            </div>
          </div>

          {/* Sentiment Health & Shift */}
          <div className="space-y-3">
            <h3 className="text-xs font-extrabold uppercase tracking-wider text-gray-400">
              2. Sentiment Pulse & Trajectory
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-slate-800/40 border border-slate-800 p-4 rounded-2xl text-center">
                <div className="text-xs text-gray-400">Overall Net Sentiment</div>
                <div className="text-3xl font-black text-emerald-400 mt-1">
                  {activeReport.sentimentAnalysis?.overallScore > 0
                    ? `+${activeReport.sentimentAnalysis?.overallScore}`
                    : activeReport.sentimentAnalysis?.overallScore}
                </div>
              </div>

              <div className="bg-slate-800/40 border border-slate-800 p-4 rounded-2xl text-center">
                <div className="text-xs text-gray-400">Positive vs Negative</div>
                <div className="text-xl font-bold text-white mt-2">
                  <span className="text-emerald-400">{activeReport.sentimentAnalysis?.positivePercent}%</span> vs{' '}
                  <span className="text-red-400">{activeReport.sentimentAnalysis?.negativePercent}%</span>
                </div>
              </div>

              <div className="bg-slate-800/40 border border-slate-800 p-4 rounded-2xl">
                <div className="text-xs text-gray-400 font-semibold mb-1">Sentiment Shift Callout</div>
                <p className="text-xs text-gray-300 font-medium">
                  {activeReport.sentimentAnalysis?.sentimentShift}
                </p>
              </div>
            </div>
          </div>

          {/* Top Customer Themes */}
          <div className="space-y-3">
            <h3 className="text-xs font-extrabold uppercase tracking-wider text-gray-400">
              3. Top Customer Discussion Themes
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {activeReport.topThemes?.map((th, idx) => (
                <div key={idx} className="bg-slate-800/40 border border-slate-800 p-4 rounded-2xl space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-white text-xs">{th.name}</span>
                    <span className="text-[10px] font-extrabold bg-indigo-950 text-indigo-300 px-2 py-0.5 rounded border border-indigo-800">
                      {th.trend}
                    </span>
                  </div>
                  <p className="text-xs text-gray-300 leading-relaxed font-normal">{th.keyInsight}</p>
                  <div className="text-[11px] text-gray-400 font-semibold">{th.count} customer mentions</div>
                </div>
              ))}
            </div>
          </div>

          {/* Verbatim Quotes */}
          <div className="space-y-3">
            <h3 className="text-xs font-extrabold uppercase tracking-wider text-gray-400">
              4. Key Verbatim Customer Quotes
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {activeReport.sampleQuotes?.map((q, idx) => (
                <div key={idx} className="bg-slate-800/40 border border-slate-800 p-4 rounded-2xl space-y-2 text-xs">
                  <div className="flex items-center justify-between text-[11px] text-gray-400">
                    <span className="font-bold text-indigo-400">{q.channel}</span>
                    <span className="font-semibold text-gray-400">{q.impact}</span>
                  </div>
                  <p className="text-gray-200 italic font-medium">"{q.quote}"</p>
                </div>
              ))}
            </div>
          </div>

          {/* Recommended Product & Engineering Actions */}
          <div className="space-y-3">
            <h3 className="text-xs font-extrabold uppercase tracking-wider text-gray-400">
              5. Prioritized Action Items
            </h3>
            <div className="space-y-2.5">
              {activeReport.recommendedActions?.map((act, idx) => (
                <div
                  key={idx}
                  className="bg-slate-800/60 border border-slate-700/80 p-4 rounded-2xl flex flex-wrap items-center justify-between gap-4 text-xs"
                >
                  <div className="space-y-1 flex-1 min-w-[260px]">
                    <div className="flex items-center gap-2">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-extrabold ${
                          act.priority === 'HIGH'
                            ? 'bg-red-500/20 text-red-400 border border-red-500/30'
                            : 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                        }`}
                      >
                        {act.priority} PRIORITY
                      </span>
                      <span className="text-gray-400 font-bold">• Target Team: {act.targetTeam}</span>
                    </div>
                    <p className="text-white font-bold">{act.action}</p>
                    <p className="text-gray-400 text-[11px]">Expected Impact: {act.expectedImpact}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      ) : (
        <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-16 text-center space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-indigo-950 border border-indigo-800 flex items-center justify-center text-indigo-400 mx-auto">
            <FileText className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-extrabold text-white">No VoC Reports Generated Yet</h3>
            <p className="text-xs text-gray-400 mt-1 max-w-sm mx-auto">
              Click "Generate VoC Report" to synthesize your initial executive leadership intelligence digest.
            </p>
          </div>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold px-5 py-2.5 rounded-xl shadow-lg shadow-indigo-600/30 inline-flex items-center gap-2"
          >
            <Sparkles className="w-4 h-4" />
            <span>Generate First Report</span>
          </button>
        </div>
      )}
    </div>
  );
}
